---
- hosts: nfs
  become: yes
  tasks:
  - name: install nfs utils
    shell: dnf install nfs-utils -y
    register: output

  - name: install nfs tools
    shell: dnf install net-tools -y
    register: output