---
- hosts: nfs
  become: yes
  tasks:
  - name: install nfs utils
    shell: dnf install nfs-utils
    register: output

  - name: install nfs tools
    shell: dnf install nfs-tools
    register: output