---
- hosts: nfs
  become: yes
  tasks:
  - name: install nfs utils
    shell: dnf install nfs-utils -y
    register: output

  - name: install net tools
    shell: dnf install net-tools -y
    register: output
  
  - name: start nfs servvice
    shell: systemctl start nfs-server.servvice
    register: output
  
  - name: check server status
    shell: systemctl status nfs-server.servvice
    register: output